name: "Visual Diffs"

on:
  push:
    branches: [ "master", "migurski/add-visual-diff-comments" ]
  pull_request:
    branches: [ "master", "migurski/add-visual-diff-comments" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    env:
      API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}

    steps:
        - name: Output some env vars
          run: |
            echo PWD: $PWD
            echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
            echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
            echo GITHUB_SHA: $GITHUB_SHA
            echo GITHUB_REF: $GITHUB_REF
            echo GITHUB_SERVER_URL: $GITHUB_SERVER_URL
            echo GITHUB_API_URL: $GITHUB_API_URL
        - name: Who am I?
          run: |
            curl https://api.github.com/user -H "Authorization: token ${API_ACCESS_TOKEN}"
        - name: Setup Python3 and GDAL
          run: |
            sudo apt-get update
            sudo apg-get install -y python3-pip python3-gdal
        - name: Get needed packages
          run: |
            python3 --version
            pip3 install flask
